### ISSUE TITLE
Adding support for proper layout margins, XAML-style

### ISSUE THREAD

**Issue by igor-makarov** [gk-brown/MarkupKit#60] opened 2016-08-22 12:19 UTC
Assume I have the following layout:
```xml
<LMColumnView spacing="0">
    <UILabel text="Big" font="System 15"/>
    <UILabel text="Small" font="System 8" />
</LMColumnView>
```

If I wanted to add a leading space of 10 units to the first view only, I'd be out of luck. Only way to do it is by adding a `LMRowView` like so:
```xml
<LMColumnView spacing="0">
    <LMRowView spacing="0">
        <LMSpacer width="10"/>
        <UILabel text="Big" font="System 15"/>
    </LMRowView>
    <UILabel text="Small" font="System 8" />
</LMColumnView>
```
...which is cumbersome. I suggest supporting the following syntax:
```xml
<LMColumnView spacing="0">
    <UILabel margin="0 0 0 10" text="Big" font="System 15"/>
    <UILabel text="Small" font="System 8" />
</LMColumnView>
```
Where `margin` will be decoded to UIEdgeInsets and interpreted by superview when performing layout. It will support RTL by mapping `UIEdgeInsets.left`/`UIEdgeInsets.right` properties to Leading/Trailing constraints respectively.

**Comment by gk-brown** [comment] 2016-08-22 12:55
This is actually by design. MarkupKit doesn't make a distinction between "padding" and "margin" like some other toolkits do. Instead, it uses "layout margins" (defined by UIKit) and "spacing" (provided by MarkupKit).

While this may make certain layouts slightly more verbose, it keeps the framework simple, both to implement and to document. In practice, I haven't found it to be a major limitation. In fact, I've found Android's lack of a "spacing" concept to be much more frustrating.

**Comment by gk-brown** [comment] 2016-08-22 13:14
By the way, another option is to use a nested row view with a `layoutMarginLeft` value. For example:

```xml
<LMColumnView spacing="0">
    <LMRowView layoutMarginLeft="10">
        <UILabel text="Big" font="System 15"/>
    </LMRowView>
    <UILabel text="Small" font="System 8" />
</LMColumnView>
```
This way, you wouldn't need the extra `LMSpacer` view.

**Comment by igor-makarov** [comment] 2016-08-22 13:15
While the considerations are understandable, in my experience there hasn't been much use to layout margins, for two reasons:

1.  Designers like being in control of individual margins for elements and layout margins are applied on the superview level.
2.  They are not RTL-capable. Our userbase consists of a significant number of RTL users so anything that doesn't understand Leading/Trailing isn't used.

**Comment by gk-brown** [comment] 2016-08-22 13:29
I know that some other toolkits do apply layout margins at the superview level and padding at the subview level. However, in iOS layout margins are more akin to padding, and spacer views are often used to create space (either fixed or flexible) between views. The `spacing` property (supported by `LMRowView`, `LMColumnView`, and UIKit's `UIStackView` class) can also be used to create space between views.

Since MarkupKit is an iOS-specific framework, I've tried to make it as consistent with existing platform conventions as possible. That means that it needs to support UIKit's definition of "layout margins", and it needs to mirror behaviors users will expect from `UIStackView` (such as `spacing`). This does imply that you may need to do things slightly differently than you might on other platforms, but I think this is preferable to the confusion that breaking with established platform conventions might create.

Given your RTL requirements, a leading `LMSpacer` view seems like the right approach.

**Comment by gk-brown** [comment] 2016-08-22 13:40
Just out of curiosity, have you tried using layout margins with an RTL locale? `LMRowView` does apply an `NSLayoutAttributeLeadingMargin` constraint to the first subview when `layoutMarginsRelativeArrangement` is `true` (the default), so it could work. I'll give it a try myself when I get a chance.

**Comment by igor-makarov** [comment] 2016-08-22 13:43
Layout margins are exactly what gave me grief on RTL. The auto layout constraints may be leading/trailing, but if your left margin is 10 and the right is 20, it will stay left and right no matter RTL state.

Layout margins seem to predate auto layout's RTL support on iOS.

**Comment by gk-brown** [comment] 2016-08-22 13:47
That's possible (and unfortunate). I'll try it out myself and will let you know if I learn anything useful.

**Comment by gk-brown** [comment] 2016-08-22 14:06
You appear to be correct. The left/right layout margins do not seem to respect RTL layouts. That seems like a major oversight on Apple's part. It definitely limits the usefulness of layout margins, at least in situations where the left and right margins are different.

It is unfortunate, but on the other hand it is a good use case for spacer views inside of row views.

**Comment by igor-makarov** [comment] 2016-08-22 16:42
I doubt they ever will, just like you don't expect them to make `.frame` RTL-compliant.

Which is why I always set layout margins to 0 and just lay everything with autolayout.

**Comment by gk-brown** [comment] 2016-08-22 19:16
Unless there's any objection, I'm going to close this issue. I'm glad that you brought it up because it is definitely a shortcoming that I wasn't aware of. However, since it's an issue that applies to all iOS applications, not just MarkupKit apps, I think it is best left to Apple to resolve.

However, I will keep it in mind. If I can come up with a better solution than using spacer views, I'll reopen the issue.

**Closed by gk-brown** 2016-08-22 19:16 UTC

**Comment by gk-brown** [comment] 2017-07-05 17:14
FWIW, this is now supported in MarkupKit. The `leadingSpacing` and `trailingSpacing` properties can be used to specify locale-aware padding. Layout margins in iOS 11 are also optionally locale-aware.
